//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoRentalCarClient.RentalcarReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RentalcarReference.IReservations")]
    public interface IReservations {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservations/Check", ReplyAction="http://tempuri.org/IReservations/CheckResponse")]
        bool Check(int vehicleClass, int location, string dates);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservations/Reserve", ReplyAction="http://tempuri.org/IReservations/ReserveResponse")]
        int Reserve(int vehicleClass, int location, string dates);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservations/Cancel", ReplyAction="http://tempuri.org/IReservations/CancelResponse")]
        bool Cancel(int confirmationNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservationsChannel : DemoRentalCarClient.RentalcarReference.IReservations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservationsClient : System.ServiceModel.ClientBase<DemoRentalCarClient.RentalcarReference.IReservations>, DemoRentalCarClient.RentalcarReference.IReservations {
        
        public ReservationsClient() {
        }
        
        public ReservationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Check(int vehicleClass, int location, string dates) {
            return base.Channel.Check(vehicleClass, location, dates);
        }
        
        public int Reserve(int vehicleClass, int location, string dates) {
            return base.Channel.Reserve(vehicleClass, location, dates);
        }
        
        public bool Cancel(int confirmationNumber) {
            return base.Channel.Cancel(confirmationNumber);
        }
    }
}
